---
title: "Study 1"
output:
  word_document: default
  pdf_document: default
---

This file reproduces the preprocessing and analysis steps of Study 1. The data are automatically imported from Github and necessary packages will be downloaded and installed if they are not yet available. 


```{r,echo=F,message=F,warning=F}
rm(list=ls())
if (!require("pacman"))
  install.packages("pacman")
required_packages = c("tidyverse",
                      "readbulk",
                      'jmv',
                      'afex',
                      'BayesFactor',
                      'brms',
                      'emmeans',
                      'psych')
pacman::p_load(required_packages,
               update = F,
               character.only = T)
```


```{r}
sessionInfo()
```

## Import data


```{r}
df = read.csv('https://raw.githubusercontent.com/mertensu/thinking-in-ratios/master/data_total_study1.csv')
```


## Preprocessing

```{r}
# replace zero ratings with 0.001
df[df$brightness_rating==0,'brightness_rating'] = 0.001

# make rating comparable across conditions
df[, "brightness_rating"] = ifelse(df$condition == "reversal",
                                   10 * (10 / df$brightness_rating),
                                   df$brightness_rating
)
# compute log rating
df$log_brightness_rating = log(df$brightness_rating)
```


## Demographics

```{r}
psych::describe(df$age)

df %>% distinct(File, .keep_all = T) %>% group_by(gender) %>% summarise(
  N = n(),
  Min =
    min(age),
  Max =
    max(age),
  Mean =
    mean(age),
  Sd =
    sd(age)
)
df %>% distinct(File, .keep_all = T) %>% count(student)
df %>% distinct(File, .keep_all = T) %>% filter(student == 1) %>% count(psycho)
```


## Analysis

### ANOVA I (within 2 (method) x 8(luminance))

#### frequentist fit

```{r, message=F, warning=F}
# 
df$cd_factor = factor(df$cd, levels = c(1, 1.8, 3.2, 5.7, 17.9, 32.0, 57.2, 100.0))
(fit = aov_ez(
  dv = 'log_brightness_rating',
  within = c('condition', 'cd_factor'),
  id = 'File',
  data = df
))
```

#### bayesian fit

```{r,message=F, warning=F}
df_sub = df %>% select(log_brightness_rating, condition, cd_factor, File)
df_sub$condition = factor(df_sub$condition)
df_sub$File = factor(df_sub$File)
bfs = anovaBF(
  log_brightness_rating ~ condition * cd_factor + File,
  whichRandom = 'File',
  whichModels = 'top',
  data = df_sub
)


# BF cd_stepwise_distance
bf_1 = lmBF(log_brightness_rating ~ condition + File,
            whichRandom = 'File',
            data = df_sub)
bf_2 = lmBF(
  log_brightness_rating ~ cd_factor + condition + File,
  whichRandom = 'File',
  data = df_sub
)
(bf_cd_factor = bf_2 / bf_1)
print(paste0('logBF ', bf_cd_factor@bayesFactor$bf))


# BF condition
bf_1 = lmBF(log_brightness_rating ~ cd_factor + File,
            whichRandom = 'File',
            data = df_sub)
bf_2 = lmBF(
  log_brightness_rating ~ cd_factor + condition + File,
  whichRandom = 'File',
  data = df_sub
)
(bf_condition = bf_2 / bf_1)
print(paste0('logBF ', bf_condition@bayesFactor$bf))

# BF interaction
bf_1 = lmBF(
  log_brightness_rating ~ cd_factor + condition + File,
  whichRandom = 'File',
  data = df_sub
)
bf_2 = lmBF(
  log_brightness_rating ~ cd_factor * condition + File,
  whichRandom = 'File',
  data = df_sub
)
(bf_interaction = bf_2 / bf_1)
print(paste0('logBF ', bf_interaction@bayesFactor$bf))
```

### Figure 1

```{r}
scaleFUN <- function(x)
  sprintf("%.1f", x)

grid = data.frame(emmeans(fit,  ~ cd_factor + condition))

ggplot(grid, aes(
  x = cd_factor,
  y = exp(emmean),
  group = condition
)) +
  geom_pointrange(aes(
    ymin = exp(lower.CL),
    ymax = exp(upper.CL),
    color = condition
  ), size =
    0.3) +
  scale_y_continuous(
    trans = 'log2',
    breaks = c(1.0, 10.0, 100.0, 1000.0),
    limits = c(1.0, 1000.0),
    labels = scaleFUN
  ) +
  geom_line(linetype = 'dashed') +
  labs(y = 'Brightness judgement') +
  xlab(expression(paste("cd/", m ^ 2, sep = ""))) +
  scale_color_manual(
    values = c("darkgrey", "black"),
    name = "method",
    labels = c("reversal", "standard")
  ) +
  scale_x_discrete(labels = substring(grid$cd_factor, 2)) +
  theme_classic() +
  theme(
    legend.position = c(0.2, 0.8),
    legend.background = element_rect(color = "black")
  )
```


```{r}
ggsave(
  paste0("final_plots/study1_figure1.png"),
  dpi = 600,
  height = 4,
  width = 5,
  units = "in"
)
```

